---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: ingress-nginx
  name: ingress-nginx
spec:
  minAvailable: 60%
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx