name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - feat/prometheus-integration
  paths:
    exclude:
    - README.md
pr:
  branches:
    include:
    - feat/prometheus-integration
stages:
- template: build.yaml
- template: deploy.yaml