name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - azure/src/services/*
    exclude:
    - README.md
    - gcp/*
    - azure/src/baseline/*
pr:
  branches:
    include:
    - master
stages:
- template: build.yaml
- template: deploy.yaml