---
- hosts: localhost
  connection: local
  gather_facts: no
  name: Configure Financial Products Kubernetes Clusters
  tasks:

    - name: "Configure ingress to aks 1"
      import_role: 
        name: stone-payments.aks
      vars:
        aks_service_principal_app_id: "{{ lookup('env','TF_VAR_service_principal_app_id') }}"
        aks_service_principal_password: "{{ lookup('env','TF_VAR_service_principal_password') }}"
        aks_registry_url: "{{ lookup('env','aks_registry_url') }}"
        aks_kubeconfig_path: "ins_kube_config_raw_aks1"
        aks_rbac_developers_role: "edit"
        aks_rbac_developers_aad_group: "{{ lookup('env','aks_rbac_developers_aad_group') }}"
        aks_monitoring_domain: "dev.dca.financialproducts.stone.com.br"
        aks_default_certificate_key_path: "{{ lookup('env','aks_default_certificate_key_path') }}"
        aks_default_certificate_path: "{{ lookup('env','aks_default_certificate_path') }}"
        grafana_name: "grafana-inside-cl1"
        prometheus_name: "alertmanager-inside-cl1"
        alertmanager_name: "prometheus-inside-cl1"

    - name: "Configure ingress to aks 2"
      import_role: 
        name: stone-payments.aks
      vars:
        aks_service_principal_app_id: "{{ lookup('env','TF_VAR_service_principal_app_id') }}"
        aks_service_principal_password: "{{ lookup('env','TF_VAR_service_principal_password') }}"
        aks_registry_url: "{{ lookup('env','aks_registry_url') }}"
        aks_kubeconfig_path: "ins_kube_config_raw_aks2"
        aks_rbac_developers_role: "edit"
        aks_rbac_developers_aad_group: "{{ lookup('env','aks_rbac_developers_aad_group') }}"
        aks_monitoring_domain: "dev.dca.financialproducts.stone.com.br"
        aks_default_certificate_key_path: "{{ lookup('env','aks_default_certificate_key_path') }}"
        aks_default_certificate_path: "{{ lookup('env','aks_default_certificate_path') }}"
        grafana_name: "grafana-inside-cl2"
        prometheus_name: "alertmanager-inside-cl2"
        alertmanager_name: "prometheus-inside-cl2"        